title: Belform Insulation
email: chantal@belform.com
description: >- # this means to ignore newlines until "baseurl:"
  Belform Insulation offers an extensive range of high-quality mechanical insulation products in Canada, tailored to meet the diverse needs of various industries across Canada. Our product line includes Belform Insul-Phen, Belform Styrofoam Interlocking System, and Trymer XP Pipe Insulation & Fittings.

author:
  name: "Belform Insulation"
  email: "chantal@belform.com"
  url: "https://belform.com"

baseurl: /
source: .
destination: ./_site

collections:
  belform_products:
    output: true
    permalink: /products/:slug
  belform_projects:
      output: true
      permalink: /projects/:slug

author:
  name: "Belform Insulation Canada"
  email: "belforminsulation@gmail.com"
  url: "https://www.belform.com"

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Custom variables
owner : "Belform Insulation"
year : "2024"

favicon-url: assets/images/favicon.ico
